version: '3'
services:
  app:
    container_name: node-mongo
    restart: always
    build: .
    ports:
      - "4000:4000"
    external_links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /tmp/db:/data/db
    # networks:
    #   - app