version: '3'
services:
  app:
    container_name: node-mongo
    restart: always
    build: .
    ports:
      - "4000:3000"
    external_links:
      - mongo
    volumes:
      - .:/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - /tmp/db:/data/db
    # networks:
    #   - app