export const AUTH_TYPES = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_LOADING: "LOGIN_LOADING",
    LOGOUT_LOADING: "LOGOUT_LOADING",
    LOGGED_OUT: "LOGGED_OUT",
    USER_LOADED_FROM_TOKEN: "USER_LOADED_FROM_TOKEN",
    GET_USERS: "GET_USERS",
    AUTH_ERROR: "AUTH_ERROR",
    LOGIN_FAILED: "LOGIN_FAILED",
  };
  